/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as PalcoRouteImport } from './routes/palco'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as ProjetorRouteImport } from './routes/projetor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const PalcoRoute = PalcoRouteImport.update({
  id: '/palco',
  path: '/palco',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetorRoute = ProjetorRouteImport.update({
  id: '/projetor',
  path: '/projetor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instalar': typeof InstalarRoute
  '/palco': typeof PalcoRoute
  '/pedido': typeof PedidoRoute
  '/projetor': typeof ProjetorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instalar': typeof InstalarRoute
  '/palco': typeof PalcoRoute
  '/pedido': typeof PedidoRoute
  '/projetor': typeof ProjetorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instalar': typeof InstalarRoute
  '/palco': typeof PalcoRoute
  '/pedido': typeof PedidoRoute
  '/projetor': typeof ProjetorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instalar' | '/palco' | '/pedido' | '/projetor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instalar' | '/palco' | '/pedido' | '/projetor'
  id: '__root__' | '/' | '/instalar' | '/palco' | '/pedido' | '/projetor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstalarRoute: typeof InstalarRoute
  PalcoRoute: typeof PalcoRoute
  PedidoRoute: typeof PedidoRoute
  ProjetorRoute: typeof ProjetorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palco': {
      id: '/palco'
      path: '/palco'
      fullPath: '/palco'
      preLoaderRoute: typeof PalcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetor': {
      id: '/projetor'
      path: '/projetor'
      fullPath: '/projetor'
      preLoaderRoute: typeof ProjetorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstalarRoute: InstalarRoute,
  PalcoRoute: PalcoRoute,
  PedidoRoute: PedidoRoute,
  ProjetorRoute: ProjetorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
